# Generated by Django 3.2.13 on 2022-06-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('version', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('csv', models.FileField(default='Anomaly Simulation with tzinfo v0.csv', upload_to='')),
            ],
        ),
    ]
