# Generated by Django 3.2.5 on 2022-04-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_spring', '0002_test_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(default='default_image.jpeg', upload_to=''),
        ),
    ]
