# Generated by Django 3.2.5 on 2022-04-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_spring', '0004_csv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSV',
        ),
        migrations.AddField(
            model_name='test',
            name='csv',
            field=models.CharField(default='Anomaly Simulation with tzinfo.csv', max_length=200),
        ),
    ]
