# Generated by Django 3.2.5 on 2022-04-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_spring', '0005_auto_20220424_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='csv',
            field=models.FileField(default='Anomaly Simulation with tzinfo.csv', upload_to=''),
        ),
    ]
