# Generated by Django 4.0.4 on 2022-06-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_spring', '0006_alter_test_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='image',
        ),
        migrations.RemoveField(
            model_name='test',
            name='text',
        ),
        migrations.RemoveField(
            model_name='test',
            name='title',
        ),
        migrations.AddField(
            model_name='test',
            name='version',
            field=models.CharField(default='v0', max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='csv',
            field=models.FileField(default='Anomaly Simulation with tzinfo v0.csv', upload_to=''),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
