# Generated by Django 4.0.4 on 2022-06-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_spring', '0007_remove_test_image_remove_test_text_remove_test_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='id',
        ),
        migrations.AlterField(
            model_name='test',
            name='version',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
